"use client";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/Components/NavBar";
import Login from "./login/page";
import { ThemeProvider } from "@emotion/react";
import BitcoinRates from "./bitcoinRates/page";
import { tealTheme } from "@/Components/CustomTheme";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={tealTheme}>
          <NavBar>
            <Login />
            <BitcoinRates />
          </NavBar>
        </ThemeProvider>
        {children}
      </body>
    </html>
  );
}
